=== JohanSantanaGalvan/Project01/Actividad 4/Tarea 4.dtd
<!ELEMENT Pedidos (Pedido)>
<!ELEMENT Pedido (Pizzas, Direccion, NombreDelCliente)>
<!ELEMENT Direccion (#PCDATA)>
<!ELEMENT NombreDelCliente (#PCDATA)>
<!ELEMENT Pizzas (Pizza+)>
<!ELEMENT Pizza (NombreDePizza+, Ingredienteadicional, Cantidad+)>
<!ELEMENT NombreDePizza  (#PCDATA)>
<!ELEMENT Ingredienteadicional (#PCDATA)>
<!ELEMENT Cantidad (#PCDATA)>

=== JohanSantanaGalvan/Project01/Actividad 4/Tarea 4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Pedidos SYSTEM "Tarea 4.dtd">

<Pedidos>
    <Pedido>
        <Pizzas>
            <Pizza>
                <NombreDePizza>Margarita</NombreDePizza>
                <Ingredienteadicional>Pimientos Morrones</Ingredienteadicional>
                <Cantidad>1</Cantidad>
            </Pizza>

            <Pizza>
                <NombreDePizza>Artesana</NombreDePizza>
                <Ingredienteadicional>Ninguno</Ingredienteadicional>
                <Cantidad>2</Cantidad>
            </Pizza>

            <Pizza>
                <NombreDePizza>Vegetal</NombreDePizza>
                <Ingredienteadicional>Ninguno</Ingredienteadicional>
                <Cantidad>1</Cantidad>
            </Pizza>


        </Pizzas>
        <Direccion>calle Guanarteme, nº 17</Direccion>
        <NombreDelCliente>Pepe Pérez</NombreDelCliente>


    </Pedido>
</Pedidos>
